# Generated by Django 6.0.6 on 2026-07-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
